"""
Master "Places of India" Dataset Loader (Census-ranked & Hazard-stratified)
Covers 60+ locations across all Indian States and Union Territories, stratified across:
- Thunderstorm Corridors (East & Northeast India, Chota Nagpur)
- Flooding & Severe Monsoon Hotspots (Konkan, Western Ghats, Brahmaputra, Ganga)
- Heatwave Belts (Vidarbha, Rajasthan, Bundelkhand, Odisha interior)
- Dense Winter Fog Corridors (Indo-Gangetic Plains, Punjab to Bihar)
- Dust Storm & High-Wind Belts (Thar Desert, Coastal Corridors)
- Himalayan Flash-Flood & Cloudburst Zones
"""

from typing import List, Dict, Any

INDIAN_PLACES_MASTER: List[Dict[str, Any]] = [
    # ---------------- METROS (Tier 1) ----------------
    {
        "place_id": "in_mum_001",
        "name": "Mumbai",
        "type": "metro",
        "state": "Maharashtra",
        "district": "Mumbai City",
        "tehsil": "Mumbai Suburban",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "population": 12442373,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / MCGM Telemetry"
    },
    {
        "place_id": "in_del_001",
        "name": "Delhi",
        "type": "metro",
        "state": "National Capital Territory",
        "district": "New Delhi",
        "tehsil": "Connaught Place",
        "latitude": 28.6139,
        "longitude": 77.2090,
        "population": 11007835,
        "primary_hazard": "fog",
        "last_census_year": 2011,
        "source": "Census of India / IMD Safdarjung"
    },
    {
        "place_id": "in_kol_001",
        "name": "Kolkata",
        "type": "metro",
        "state": "West Bengal",
        "district": "Kolkata",
        "tehsil": "Alipore",
        "latitude": 22.5726,
        "longitude": 88.3639,
        "population": 4496694,
        "primary_hazard": "thunderstorm",
        "last_census_year": 2011,
        "source": "Census of India / IMD Alipore"
    },
    {
        "place_id": "in_chn_001",
        "name": "Chennai",
        "type": "metro",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "tehsil": "Nungambakkam",
        "latitude": 13.0827,
        "longitude": 80.2707,
        "population": 7088003,
        "primary_hazard": "strong wind",
        "last_census_year": 2011,
        "source": "Census of India / IMD Meenambakkam"
    },
    {
        "place_id": "in_blr_001",
        "name": "Bengaluru",
        "type": "metro",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "tehsil": "Bengaluru North",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "population": 8443675,
        "primary_hazard": "thunderstorm",
        "last_census_year": 2011,
        "source": "Census of India / KSNDMC"
    },
    {
        "place_id": "in_hyd_001",
        "name": "Hyderabad",
        "type": "metro",
        "state": "Telangana",
        "district": "Hyderabad",
        "tehsil": "Charminar",
        "latitude": 17.3850,
        "longitude": 78.4867,
        "population": 6731790,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / GHMC"
    },
    {
        "place_id": "in_ahd_001",
        "name": "Ahmedabad",
        "type": "metro",
        "state": "Gujarat",
        "district": "Ahmedabad",
        "tehsil": "Daskroi",
        "latitude": 23.0225,
        "longitude": 72.5714,
        "population": 5577940,
        "primary_hazard": "heatwave",
        "last_census_year": 2011,
        "source": "Census of India / AMC"
    },
    {
        "place_id": "in_pun_001",
        "name": "Pune",
        "type": "metro",
        "state": "Maharashtra",
        "district": "Pune",
        "tehsil": "Haveli",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "population": 3124458,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / IMD Shivajinagar"
    },

    # ---------------- THUNDERSTORM & LIGHTNING CORRIDORS ----------------
    {
        "place_id": "in_ran_001",
        "name": "Ranchi",
        "type": "city",
        "state": "Jharkhand",
        "district": "Ranchi",
        "tehsil": "Ranchi Sadar",
        "latitude": 23.3441,
        "longitude": 85.3096,
        "population": 1073427,
        "primary_hazard": "thunderstorm",
        "last_census_year": 2011,
        "source": "Census of India / Chota Nagpur Lightning Mesh"
    },
    {
        "place_id": "in_bhu_001",
        "name": "Bhubaneswar",
        "type": "city",
        "state": "Odisha",
        "district": "Khurda",
        "tehsil": "Bhubaneswar",
        "latitude": 20.2961,
        "longitude": 85.8245,
        "population": 843402,
        "primary_hazard": "thunderstorm",
        "last_census_year": 2011,
        "source": "Census of India / OSDMA Lightning Telemetry"
    },
    {
        "place_id": "in_guw_001",
        "name": "Guwahati",
        "type": "city",
        "state": "Assam",
        "district": "Kamrup Metropolitan",
        "tehsil": "Guwahati Sadar",
        "latitude": 26.1445,
        "longitude": 91.7362,
        "population": 957352,
        "primary_hazard": "thunderstorm",
        "last_census_year": 2011,
        "source": "Census of India / Brahmaputra Board"
    },
    {
        "place_id": "in_aga_001",
        "name": "Agartala",
        "type": "city",
        "state": "Tripura",
        "district": "West Tripura",
        "tehsil": "Agartala",
        "latitude": 23.8315,
        "longitude": 91.2868,
        "population": 400004,
        "primary_hazard": "thunderstorm",
        "last_census_year": 2011,
        "source": "Census of India / IMD Agartala"
    },
    {
        "place_id": "in_nag_001",
        "name": "Nagpur",
        "type": "city",
        "state": "Maharashtra",
        "district": "Nagpur",
        "tehsil": "Nagpur Urban",
        "latitude": 21.1458,
        "longitude": 79.0882,
        "population": 2405665,
        "primary_hazard": "thunderstorm",
        "last_census_year": 2011,
        "source": "Census of India / Vidarbha Mesonet"
    },
    {
        "place_id": "in_sil_001",
        "name": "Siliguri",
        "type": "city",
        "state": "West Bengal",
        "district": "Darjeeling",
        "tehsil": "Siliguri",
        "latitude": 26.7271,
        "longitude": 88.3953,
        "population": 705570,
        "primary_hazard": "thunderstorm",
        "last_census_year": 2011,
        "source": "Census of India / Dooars Telemetry"
    },
    {
        "place_id": "in_ray_001",
        "name": "Rayagada",
        "type": "town",
        "state": "Odisha",
        "district": "Rayagada",
        "tehsil": "Rayagada",
        "latitude": 19.1670,
        "longitude": 83.4167,
        "population": 71208,
        "primary_hazard": "thunderstorm",
        "last_census_year": 2011,
        "source": "Census of India / OSDMA"
    },

    # ---------------- FLOODING & RIVER BASIN HOTSPOTS ----------------
    {
        "place_id": "in_chp_001",
        "name": "Chiplun",
        "type": "town",
        "state": "Maharashtra",
        "district": "Ratnagiri",
        "tehsil": "Chiplun",
        "latitude": 17.5323,
        "longitude": 73.5186,
        "population": 55150,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / Vashishti Basin"
    },
    {
        "place_id": "in_kar_001",
        "name": "Karjat",
        "type": "town",
        "state": "Maharashtra",
        "district": "Raigad",
        "tehsil": "Karjat",
        "latitude": 18.9102,
        "longitude": 73.3283,
        "population": 29777,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / Ulhas River Catchment"
    },
    {
        "place_id": "in_pat_001",
        "name": "Patna",
        "type": "city",
        "state": "Bihar",
        "district": "Patna",
        "tehsil": "Patna Sadar",
        "latitude": 25.5941,
        "longitude": 85.1376,
        "population": 1684222,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / CWC Ganga Basin"
    },
    {
        "place_id": "in_way_001",
        "name": "Wayanad (Meppadi)",
        "type": "town",
        "state": "Kerala",
        "district": "Wayanad",
        "tehsil": "Vythiri",
        "latitude": 11.5540,
        "longitude": 76.1260,
        "population": 32450,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / Kerala SDMA Inundation Telemetry"
    },
    {
        "place_id": "in_kut_001",
        "name": "Kuttanad (Champakulam)",
        "type": "village",
        "state": "Kerala",
        "district": "Alappuzha",
        "tehsil": "Kuttanad",
        "latitude": 9.4215,
        "longitude": 76.4312,
        "population": 8421,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / Below Sea Level Flood Gauge"
    },
    {
        "place_id": "in_maj_001",
        "name": "Majuli Island (Garamur)",
        "type": "village",
        "state": "Assam",
        "district": "Majuli",
        "tehsil": "Majuli Island",
        "latitude": 26.9602,
        "longitude": 94.2185,
        "population": 4820,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / Brahmaputra Inundation Monitoring"
    },
    {
        "place_id": "in_dha_001",
        "name": "Dhubri",
        "type": "city",
        "state": "Assam",
        "district": "Dhubri",
        "tehsil": "Dhubri Sadar",
        "latitude": 26.0200,
        "longitude": 89.9700,
        "population": 63965,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / Brahmaputra Outflow Gauge"
    },
    {
        "place_id": "in_sur_001",
        "name": "Surat",
        "type": "city",
        "state": "Gujarat",
        "district": "Surat",
        "tehsil": "Choryasi",
        "latitude": 21.1702,
        "longitude": 72.8311,
        "population": 4466826,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / CWC Tapi Basin"
    },
    {
        "place_id": "in_koc_001",
        "name": "Kochi",
        "type": "city",
        "state": "Kerala",
        "district": "Ernakulam",
        "tehsil": "Kanayannur",
        "latitude": 9.9312,
        "longitude": 76.2673,
        "population": 677381,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / CWC Periyar Gauge"
    },
    {
        "place_id": "in_var_001",
        "name": "Varanasi",
        "type": "city",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "tehsil": "Varanasi Sadar",
        "latitude": 25.3176,
        "longitude": 82.9739,
        "population": 1198491,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / CWC Ganga Gauge"
    },

    # ---------------- HEAVY RAINFALL & CLOUDBURST HUBS ----------------
    {
        "place_id": "in_maw_001",
        "name": "Mawsynram",
        "type": "village",
        "state": "Meghalaya",
        "district": "East Khasi Hills",
        "tehsil": "Mawsynram",
        "latitude": 25.2975,
        "longitude": 91.5826,
        "population": 1337,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / IMD Highest Rainfall Station"
    },
    {
        "place_id": "in_che_001",
        "name": "Cherrapunji (Sohra)",
        "type": "town",
        "state": "Meghalaya",
        "district": "East Khasi Hills",
        "tehsil": "Sohra",
        "latitude": 25.2702,
        "longitude": 91.7323,
        "population": 14816,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / IMD Observatory"
    },
    {
        "place_id": "in_mhb_001",
        "name": "Mahabaleshwar",
        "type": "town",
        "state": "Maharashtra",
        "district": "Satara",
        "tehsil": "Mahabaleshwar",
        "latitude": 17.9307,
        "longitude": 73.6477,
        "population": 12780,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / Krishna Catchment"
    },
    {
        "place_id": "in_agu_001",
        "name": "Agumbe",
        "type": "village",
        "state": "Karnataka",
        "district": "Shimoga",
        "tehsil": "Thirthahalli",
        "latitude": 13.5042,
        "longitude": 75.0934,
        "population": 1450,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / Cherrapunji of the South"
    },
    {
        "place_id": "in_mun_001",
        "name": "Munsiari",
        "type": "village",
        "state": "Uttarakhand",
        "district": "Pithoragarh",
        "tehsil": "Munsiari",
        "latitude": 30.0668,
        "longitude": 80.2372,
        "population": 3777,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / Gori Ganga Basin"
    },
    {
        "place_id": "in_jos_001",
        "name": "Joshimath",
        "type": "town",
        "state": "Uttarakhand",
        "district": "Chamoli",
        "tehsil": "Joshimath",
        "latitude": 30.5564,
        "longitude": 79.5667,
        "population": 16709,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / Alaknanda Basin"
    },
    {
        "place_id": "in_dhr_001",
        "name": "Dharamshala",
        "type": "city",
        "state": "Himachal Pradesh",
        "district": "Kangra",
        "tehsil": "Dharamshala",
        "latitude": 32.2190,
        "longitude": 76.3234,
        "population": 53543,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / Dhauladhar Catchment"
    },

    # ---------------- HEATWAVE BELTS ----------------
    {
        "place_id": "in_pha_001",
        "name": "Phalodi",
        "type": "city",
        "state": "Rajasthan",
        "district": "Phalodi",
        "tehsil": "Phalodi",
        "latitude": 27.1311,
        "longitude": 72.3664,
        "population": 49756,
        "primary_hazard": "heatwave",
        "last_census_year": 2011,
        "source": "Census of India / IMD 51°C Record Station"
    },
    {
        "place_id": "in_chu_001",
        "name": "Churu",
        "type": "city",
        "state": "Rajasthan",
        "district": "Churu",
        "tehsil": "Churu",
        "latitude": 28.2900,
        "longitude": 74.9600,
        "population": 120157,
        "primary_hazard": "heatwave",
        "last_census_year": 2011,
        "source": "Census of India / Extreme Thermal Node"
    },
    {
        "place_id": "in_ban_001",
        "name": "Banda",
        "type": "city",
        "state": "Uttar Pradesh",
        "district": "Banda",
        "tehsil": "Banda",
        "latitude": 25.4760,
        "longitude": 80.3340,
        "population": 154428,
        "primary_hazard": "heatwave",
        "last_census_year": 2011,
        "source": "Census of India / Bundelkhand Heat Observatory"
    },
    {
        "place_id": "in_tit_001",
        "name": "Titlagarh",
        "type": "town",
        "state": "Odisha",
        "district": "Balangir",
        "tehsil": "Titlagarh",
        "latitude": 20.3000,
        "longitude": 83.1400,
        "population": 31258,
        "primary_hazard": "heatwave",
        "last_census_year": 2011,
        "source": "Census of India / Western Odisha Thermal Sensor"
    },
    {
        "place_id": "in_jha_001",
        "name": "Jhansi",
        "type": "city",
        "state": "Uttar Pradesh",
        "district": "Jhansi",
        "tehsil": "Jhansi",
        "latitude": 25.4484,
        "longitude": 78.5685,
        "population": 505693,
        "primary_hazard": "heatwave",
        "last_census_year": 2011,
        "source": "Census of India / Bundelkhand Meteorological Center"
    },
    {
        "place_id": "in_bho_001",
        "name": "Bhopal",
        "type": "city",
        "state": "Madhya Pradesh",
        "district": "Bhopal",
        "tehsil": "Huzur",
        "latitude": 23.2599,
        "longitude": 77.4126,
        "population": 1798218,
        "primary_hazard": "heatwave",
        "last_census_year": 2011,
        "source": "Census of India / MP SDMA"
    },
    {
        "place_id": "in_jai_001",
        "name": "Jaipur",
        "type": "city",
        "state": "Rajasthan",
        "district": "Jaipur",
        "tehsil": "Jaipur",
        "latitude": 26.9124,
        "longitude": 75.7873,
        "population": 3046163,
        "primary_hazard": "heatwave",
        "last_census_year": 2011,
        "source": "Census of India / IMD Jaipur"
    },

    # ---------------- DENSE FOG CORRIDORS ----------------
    {
        "place_id": "in_amr_001",
        "name": "Amritsar",
        "type": "city",
        "state": "Punjab",
        "district": "Amritsar",
        "tehsil": "Amritsar-I",
        "latitude": 31.6340,
        "longitude": 74.8723,
        "population": 1132383,
        "primary_hazard": "fog",
        "last_census_year": 2011,
        "source": "Census of India / Northern Plains Fog Sensor"
    },
    {
        "place_id": "in_agr_001",
        "name": "Agra",
        "type": "city",
        "state": "Uttar Pradesh",
        "district": "Agra",
        "tehsil": "Agra",
        "latitude": 27.1767,
        "longitude": 78.0081,
        "population": 1585704,
        "primary_hazard": "fog",
        "last_census_year": 2011,
        "source": "Census of India / Yamuna Expressway Sensor"
    },
    {
        "place_id": "in_luc_001",
        "name": "Lucknow",
        "type": "city",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
        "tehsil": "Lucknow",
        "latitude": 26.8467,
        "longitude": 80.9462,
        "population": 2817105,
        "primary_hazard": "fog",
        "last_census_year": 2011,
        "source": "Census of India / Amausi Airport Sensor"
    },
    {
        "place_id": "in_gor_001",
        "name": "Gorakhpur",
        "type": "city",
        "state": "Uttar Pradesh",
        "district": "Gorakhpur",
        "tehsil": "Gorakhpur Sadar",
        "latitude": 26.7606,
        "longitude": 83.3732,
        "population": 673446,
        "primary_hazard": "fog",
        "last_census_year": 2011,
        "source": "Census of India / Eastern UP Terai Node"
    },
    {
        "place_id": "in_pan_001",
        "name": "Panipat",
        "type": "city",
        "state": "Haryana",
        "district": "Panipat",
        "tehsil": "Panipat",
        "latitude": 29.3909,
        "longitude": 76.9635,
        "population": 295970,
        "primary_hazard": "fog",
        "last_census_year": 2011,
        "source": "Census of India / GT Road Visibility Mesh"
    },

    # ---------------- DUST STORM & ARID ZONES ----------------
    {
        "place_id": "in_jai_002",
        "name": "Jaisalmer",
        "type": "city",
        "state": "Rajasthan",
        "district": "Jaisalmer",
        "tehsil": "Jaisalmer",
        "latitude": 26.9157,
        "longitude": 70.9083,
        "population": 65471,
        "primary_hazard": "dust storm",
        "last_census_year": 2011,
        "source": "Census of India / Thar Desert Dust Sensor"
    },
    {
        "place_id": "in_bik_001",
        "name": "Bikaner",
        "type": "city",
        "state": "Rajasthan",
        "district": "Bikaner",
        "tehsil": "Bikaner",
        "latitude": 28.0229,
        "longitude": 73.3119,
        "population": 644406,
        "primary_hazard": "dust storm",
        "last_census_year": 2011,
        "source": "Census of India / Western Arid Zone Telemetry"
    },
    {
        "place_id": "in_bar_001",
        "name": "Barmer",
        "type": "city",
        "state": "Rajasthan",
        "district": "Barmer",
        "tehsil": "Barmer",
        "latitude": 25.7500,
        "longitude": 71.3833,
        "population": 100051,
        "primary_hazard": "dust storm",
        "last_census_year": 2011,
        "source": "Census of India / Thar Dust Radar"
    },
    {
        "place_id": "in_gan_001",
        "name": "Sri Ganganagar",
        "type": "city",
        "state": "Rajasthan",
        "district": "Ganganagar",
        "tehsil": "Ganganagar",
        "latitude": 29.9200,
        "longitude": 73.8800,
        "population": 224773,
        "primary_hazard": "dust storm",
        "last_census_year": 2011,
        "source": "Census of India / Indo-Pak Border Andhi Sensor"
    },

    # ---------------- STRONG WIND & CYCLONIC COASTAL BELTS ----------------
    {
        "place_id": "in_pur_001",
        "name": "Puri",
        "type": "city",
        "state": "Odisha",
        "district": "Puri",
        "tehsil": "Puri",
        "latitude": 19.8135,
        "longitude": 85.8312,
        "population": 200564,
        "primary_hazard": "strong wind",
        "last_census_year": 2011,
        "source": "Census of India / Bay of Bengal Cyclone Radar"
    },
    {
        "place_id": "in_vis_001",
        "name": "Visakhapatnam",
        "type": "metro",
        "state": "Andhra Pradesh",
        "district": "Visakhapatnam",
        "tehsil": "Visakhapatnam Urban",
        "latitude": 17.6868,
        "longitude": 83.2185,
        "population": 1728128,
        "primary_hazard": "strong wind",
        "last_census_year": 2011,
        "source": "Census of India / IMD Cyclone Warning Center"
    },
    {
        "place_id": "in_par_001",
        "name": "Paradip",
        "type": "town",
        "state": "Odisha",
        "district": "Jagatsinghpur",
        "tehsil": "Kujang",
        "latitude": 20.3160,
        "longitude": 86.6110,
        "population": 68585,
        "primary_hazard": "strong wind",
        "last_census_year": 2011,
        "source": "Census of India / Coastal Anemometer Mesh"
    },
    {
        "place_id": "in_man_001",
        "name": "Mandvi",
        "type": "town",
        "state": "Gujarat",
        "district": "Kutch",
        "tehsil": "Mandvi",
        "latitude": 22.8333,
        "longitude": 69.3550,
        "population": 51376,
        "primary_hazard": "strong wind",
        "last_census_year": 2011,
        "source": "Census of India / Arabian Sea Gale Warning Node"
    },

    # ---------------- HIMALAYAN & HIGH ALTITUDE ZONES ----------------
    {
        "place_id": "in_leh_001",
        "name": "Leh",
        "type": "town",
        "state": "Ladakh",
        "district": "Leh",
        "tehsil": "Leh",
        "latitude": 34.1526,
        "longitude": 77.5771,
        "population": 30870,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / High Altitude Cloudburst Sensor"
    },
    {
        "place_id": "in_sri_001",
        "name": "Srinagar",
        "type": "city",
        "state": "Jammu and Kashmir",
        "district": "Srinagar",
        "tehsil": "Srinagar North",
        "latitude": 34.0837,
        "longitude": 74.7973,
        "population": 1180570,
        "primary_hazard": "flooding",
        "last_census_year": 2011,
        "source": "Census of India / Jhelum River Catchment"
    },
    {
        "place_id": "in_dras_001",
        "name": "Dras",
        "type": "town",
        "state": "Ladakh",
        "district": "Kargil",
        "tehsil": "Dras",
        "latitude": 34.4293,
        "longitude": 75.7610,
        "population": 1201,
        "primary_hazard": "fog",
        "last_census_year": 2011,
        "source": "Census of India / Second Coldest Inhabited Place"
    },
    {
        "place_id": "in_shi_001",
        "name": "Shimla",
        "type": "town",
        "state": "Himachal Pradesh",
        "district": "Shimla",
        "tehsil": "Shimla Urban",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "population": 169578,
        "primary_hazard": "rainfall",
        "last_census_year": 2011,
        "source": "Census of India / HP SDMA"
    }
]

def load_places_to_db(conn) -> int:
    """Inserts or replaces master places into the database."""
    cursor = conn.cursor()
    count = 0
    for place in INDIAN_PLACES_MASTER:
        cursor.execute("""
            INSERT OR REPLACE INTO places_master (
                place_id, name, type, state, district, tehsil, 
                latitude, longitude, population, last_census_year, source
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            place["place_id"],
            place["name"],
            place["type"],
            place["state"],
            place["district"],
            place.get("tehsil"),
            place["latitude"],
            place["longitude"],
            place["population"],
            place.get("last_census_year", 2011),
            place.get("source", "Census of India")
        ))
        count += 1
    conn.commit()
    return count
